<?php

namespace SYSOTEL\APP\ApiConnector\CmsOpenApi;

enum CmsOpenApiEnums
{

    const PROPERTY_STATUS_ACTIVE = 'ACTIVE';

    const BOOKING_TYPE_DAILY = 'DAILY';
    const BOOKING_TYPE_HOURLY = 'HOURLY';

    const PROPERTY_TYPE_HOTEL = 'HOTEL';
    const PROPERTY_TYPE_RESORT = 'RESORT';
    const PROPERTY_TYPE_HOMESTAY = 'HOMESTAY';
    const PROPERTY_TYPE_VILLA = 'VILLA';
    const PROPERTY_TYPE_APARTMENT = 'APARTMENT';
    const PROPERTY_TYPE_GUEST_HOUSE = 'GUEST_HOUSE';
    const PROPERTY_TYPE_LODGE = 'LODGE';
    const PROPERTY_TYPE_HOUSEBOAT = 'HOUSEBOAT';
    const PROPERTY_TYPE_FARM_HOUSE = 'FARM_HOUSE';
    const PROPERTY_TYPE_PALACE = 'PALACE';
    const PROPERTY_TYPE_MOTEL = 'MOTEL';
    const PROPERTY_TYPE_DHARAMSHALA = 'DHARAMSHALA';
    const PROPERTY_TYPE_COTTAGE = 'COTTAGE';
    const PROPERTY_TYPE_CAMP = 'CAMP';
    const PROPERTY_TYPE_POD = 'POD';
    const PROPERTY_TYPE_OTHER = 'OTHER';

    const SPACE_STATUS_ACTIVE = 'ACTIVE';

    const INVENTORY_ACCURACY_DAILY = 'DAILY';
    const INVENTORY_ACCURACY_HOURLY = 'HOURLY';

    const PRODUCT_STATUS_ACTIVE = 'ACTIVE';

    const MEAL_PLAN_CODE_EP = 'EP';
    const MEAL_PLAN_CODE_CP = 'CP';
    const MEAL_PLAN_CODE_MAP = 'MAP';
    const MEAL_PLAN_CODE_AP = 'AP';
}
